#!/bin/bash
# breaking out of an outer loop
for (( a = 1; a < 6; a++ ))
do 
	echo "Outer loop: $a"
for (( b = 1; b < 100; b++ ))
do
	if [ $b -gt 5 ]
	then
		break 4 
fi
echo " Inner loop: $b"
done
done
